export default {
  OTHER_CLIENT_CONNECTED: 'WSE_OTHER_CLIENT_CONNECTED',
  NOT_AUTHORIZED: 'WSE_NOT_AUTHORIZED',
  SIGN_OUT: 'WSE_SIGN_OUT',
  PROTOCOL_ERR: 'WSE_PROTOCOL_ERR',
  NO_REASON: 'WSE_NO_REASON',
  BY_CLIENT: 'WSE_BY_CLIENT',
}
